PARTITION_LAYOUT_DIR:apollo-nx = "tegra-saha-layout"
DEPENDS:append:apollo-nx = " ${PARTITION_LAYOUT_DIR}"
PARTITION_FILE:apollo-nx = "${STAGING_DATADIR}/${PARTITION_LAYOUT_DIR}/${PARTITION_LAYOUT_TEMPLATE}"
PARTITION_FILE_EXTERNAL:apollo-nx = "${STAGING_DATADIR}/${PARTITION_LAYOUT_DIR}/${PARTITION_LAYOUT_EXTERNAL}"
